### ISSUE TITLE
Live feeds not working. Socket issue

### ISSUE THREAD

**Issue by ravi14390** [algo2t/alphatrade#22]
Hi there,

Since today morning, socket is not getting connected and live feeds are not working.  Till yesterday it was working fine.

Here is my code, socket_opened is not getting True.

def SubscribeIndex():
    global isSocketRunning
    sas.start_websocket(subscribe_callback=event_handler_quote_update,
                socket_open_callback=open_callback,
                run_in_background=True)
    while(socket_opened==False):
        pass

**Comment by geekytapan** [comment]
facing same issue since yesterday.

**Comment by ronaldpaul** [comment]
Yes. Same issue. Hi @algo2t, the API live feed is not working at all. Looks like SAS Online might have blocked. But actually the web socket connection is returning 'None' without through errors.

**Comment by TrackMyToken** [comment]
yes I am also facing the same issue

**Comment by ronaldpaul** [comment]
Hi @algo2t, there is no use of this framework unless this Web socket issue is resolved. Please rectify it. Thanks for your effort.

**Comment by TrackMyToken** [comment]
I checked now, it started working

**Comment by ravi14390** [comment]
Started working now.... may be temporary issue from SaS side.
