### ISSUE TITLE
not able to generate access token

### ISSUE THREAD

**Issue by Tradertarunj** [algo2t/alphatrade#41]
I am not able to generate an access token please help in SASas online
I tried your config code but it is not able to generate access token

**Comment by himanshuevents** [comment]
Please always share some snapshot or output when you open issues. I was working on this last week and it was working fine.
The server is generally down at night, I am assuming that you tried it after 1 am and before 5 am late night.
Check if issue is reproducible due market time and close this issue if it is not reproducible
