### ISSUE TITLE
Empty DataFrame Columns: [open, high, low, close, volume] Index: [] 

### ISSUE THREAD

**Issue by eaywok** [algo2t/alphatrade#44]
nifty_bank_nse_index = sas.get_instrument_by_symbol('NSE', 'Nifty Bank')
df = sas.get_historical_candles(nifty_bank_nse_index.exchange, nifty_bank_nse_index.symbol,
                                    datetime(2022, 10, 11, 9, 15, 0), datetime.now(), interval=15,
                                    is_index=True)

print(df) 

Empty DataFrame
Columns: [open, high, low, close, volume]
Index: []

**Comment by neevgujral7** [comment]
bro got the issue resolved ? Please let me know

**Comment by algo2t** [comment]
Use the option is_index=True

```python

nifty_bank_nse_index = sas.get_instrument_by_symbol('NSE', 'Nifty Bank')
# print(nifty_bank_nse_index)
print(sas.history(nifty_bank_nse_index, datetime(2022, 2, 2, 9, 15, 0), datetime.now(), interval=30, is_index=True))


```
