### ISSUE TITLE
Unable to generate access token 

### ISSUE THREAD

**Issue by mrsprawin** [algo2t/alphatrade#46]
Giving this Error:

HTTPError                                 Traceback (most recent call last)
Input In [14], in <cell line: 10>()
      7 totp = f"{int(pin):06d}" if len(pin) <=5 else pin   
      8 print(config.access_token)
---> 10 sas = AlphaTrade(login_id=config.login_id, password=config.password, twofa=totp, access_token=config.access_token)
     11 socket_opened = False
     12 def event_handler_quote_update(message):

File ~/opt/anaconda3/lib/python3.9/site-packages/alphatrade/alphatrade.py:240, in AlphaTrade.__init__(self, login_id, password, twofa, access_token, master_contracts_to_download)
    238 if not self.__is_token_valid():
    239     self.__get_question_ids()
--> 240     self.__set_access_token()
    241 else:
    242     self.__headers['X-Authorization-Token'] = self.__access_token

File ~/opt/anaconda3/lib/python3.9/site-packages/alphatrade/alphatrade.py:309, in AlphaTrade.__set_access_token(self)
    306 response = self.reqsession.post(
    307     'https://alpha.sasonline.in/api/v2/checktwofa', json=twofa_body)
    308 if response.status_code != 200:
--> 309     raise requests.HTTPError(response.text)
    310 if 'error' in response.text:
    311     raise requests.HTTPError(response.text)

HTTPError: {"errors":{"detail":"Internal server error"}}

I think it is still asking for old format of twofa password which is not part of latest config file.
How to avoid this error?

**Comment by mrsprawin** [comment]
<img width="1104" alt="Screenshot 2022-11-14 at 11 49 19 AM" src="https://user-images.githubusercontent.com/74402717/201590320-5f3786f3-3d72-40a8-b5e8-a59f707b9104.png">

**Comment by mrsprawin** [comment]
<img width="1104" alt="Screenshot 2022-11-14 at 12 02 55 PM" src="https://user-images.githubusercontent.com/74402717/201591097-d9bea054-67db-40e5-932d-241b6c44d5b8.png">

**Comment by ronaldpaul** [comment]
Hi @mrsprawin, through the latest update for TOTP, should we enter the TOTP everyday in the configuration file or it will automatically do it as earlier? Because today it was sending OTP to my mobile since I am using the existing library and not the latest update (done 7 days ago) with the TOTP code. How do I update it?

Thanks

**Comment by mrsprawin** [comment]
remove your account from authenticator app and Copy the Code key from the website
<img width="846" alt="Screenshot 2022-11-14 at 1 23 20 PM" src="https://user-images.githubusercontent.com/74402717/201604865-6063cd61-2974-498d-9125-f1596b379729.png">

's the QR code prompt before scanning the QR Code.

**Comment by nevatia** [comment]
You dont seem to have/had access_token.txt file. Create one.

**Comment by yogeshdewangan** [comment]
I am also getting below error

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "E:\MyProjects\alphatrade_intraday\symbol_price.py", line 3, in <module>
    import sas_live_feed
  File "E:\MyProjects\alphatrade_intraday\sas_live_feed.py", line 25, in <module>
    sas = AlphaTrade(login_id=login_id, password=password, twofa=tot, access_token=access_token)
  File "E:\MyProjects\alphatrade_intraday\venv\lib\site-packages\alphatrade\alphatrade.py", line 240, in __init__
    self.__set_access_token()
  File "E:\MyProjects\alphatrade_intraday\venv\lib\site-packages\alphatrade\alphatrade.py", line 309, in __set_access_token
    raise requests.HTTPError(response.text)
requests.exceptions.HTTPError: {"errors":{"detail":"Internal server error"}}


I have already created access_token.txt file. Please help.

**Comment by algo2t** [comment]
This is fixed with the new version v1.0.0, `pip install -U alphatrade`
Take a look at the updated README
