### ISSUE TITLE
how to give NFO Orders ? 

### ISSUE THREAD

**Issue by shubhvashishth** [algo2t/alphatrade#48]
print ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%2%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
print(
   sas.place_order(transaction_type = TransactionType.Sell,
                     instrument = sas.get_instrument_by_symbol('NFO', 'BANKNIFTY2311241600PE'),
                     quantity = 1,
                     order_type = OrderType.Market,
                     product_type = ProductType.Delivery,
                     price = 0.0,
                     trigger_price = None,
                     stop_loss = None,
                     square_off = None,
                     trailing_sl = None,
                     is_amo = False)
)

The above code should have placed the order but instead its saying instrument not found. Am I doing it wrong or its flawed?

**Comment by nevatia** [comment]
Try like this 
instrument = sas.get_instrument_by_symbol('NFO', 'BANKNIFTY 19 JAN23 41600.0 PE'),

**Comment by nevatia** [comment]
> 

Try like this
instrument = sas.get_instrument_by_symbol('NFO', 'BANKNIFTY 19 JAN23 41600.0 PE'),

**Comment by algo2t** [comment]
ProductType is not Delivery
