### ISSUE TITLE
API hit limit/min for multiple account

### ISSUE THREAD

**Issue by harshnyadav** [algo2t/alphatrade#54]
Api hits allowed per account is 60+ hits/min. But when 2 accounts are used consecutively, the hit limit remains the same i.e. 60 hits/min but for both accounts combined, ideally, API hit should be exclusive of the account.
API can not be hit more than 60 times /min using 2 accounts exclusively.
If both accounts are run simultaneously,a error occurs after 30 hits of too many requests,

Can we play with  IP addresses or headers to resolve this issue?

**Comment by algo2t** [comment]
Out of scope for this python package, better if you connect with Dr on AlgoTradeAnalysis group on telegram
